---
monitoring_stack_dir: "/opt/monitoring"
monitoring_timezone: "Europe/Oslo"

influxdb_username: "admin"
influxdb_org: "lanilsen"
influxdb_bucket: "homelab"
influxdb_retention: "30d"

opensearch_initial_admin_password: "ChangeMe-Set-In-Ansible-Vault"
grafana_admin_password: "ChangeMe-Set-In-Ansible-Vault"

telegraf_influxdb_url: "http://127.0.0.1:8086"
telegraf_influxdb_org: "{{ influxdb_org }}"
telegraf_influxdb_bucket: "{{ influxdb_bucket }}"
telegraf_ping_targets:
  - "1.1.1.1"
telegraf_x509_targets:
  - "https://docs.lanilsen.com:443"

monitoring_snmp_enabled: false
monitoring_snmp_community: "{{ snmp_community | default('') }}"
monitoring_snmp_targets: []
