---
- name: Deploy central monitoring stack
  hosts: monitoring
  become: true
  vars_files:
    - ../group_vars/monitoring.yml
    - ../group_vars/monitoring_secrets.yml
  roles:
    - docker_host
    - monitoring_stack

- name: Deploy Telegraf agents
  hosts: telegraf_agents
  become: true
  vars_files:
    - ../group_vars/monitoring_secrets.yml
  roles:
    - telegraf_agent

- name: Deploy syslog forwarders
  hosts: syslog_forwarders
  become: true
  roles:
    - syslog_forwarder

- name: Deploy Filebeat log shippers
  hosts: log_shipper_agents
  become: true
  vars_files:
    - ../group_vars/monitoring.yml
  roles:
    - log_shipper
