---
- name: Deploy central monitoring stack
  hosts: monitoring
  become: true
  vars_files:
    - ../group_vars/monitoring_secrets.yml
  roles:
    - docker_host
    - monitoring_stack

- name: Deploy Telegraf agents
  hosts: telegraf_agents
  become: true
  vars_files:
    - ../group_vars/monitoring_secrets.yml
  roles:
    - telegraf_agent
